//! CLI 服务：注册 `dsh` 命令 shim 到系统 PATH。
//!
//! - Windows：生成 `~/.dsh/bin/dsh.cmd`，并把该目录写入用户 PATH（注册表 HKCU\\Environment）
//! - macOS/Linux：生成 `~/.local/bin/dsh`，并把 PATH 追加到 ~/.bashrc / ~/.zshrc（带标记块，幂等）
//!
//! 不覆盖用户已有 shell 配置——只做「存在检测 + 追加」。

use std::path::PathBuf;

use serde::Serialize;

use crate::error::{AppError, AppResult};
use crate::utils::path;

/// CLI 安装状态。
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CliStatus {
    pub shim_path: Option<String>,
    pub bin_dir_in_path: bool,
    pub installed: bool,
    pub message: String,
}

const SHELL_BLOCK_BEGIN: &str = "# >>> dsh-tauri-desktop >>>";
const SHELL_BLOCK_END: &str = "# <<< dsh-tauri-desktop <<<";

/// Windows 批处理 shim 内容（转发全部参数给 dsh 核心）。
fn cmd_shim_content(entry: &str) -> String {
    format!(
        "@echo off\r\nrem Generated by dsh-tauri-desktop. Safe to delete.\r\n\"node\" \"{entry}\" %*\r\n"
    )
}

/// Unix shell shim 内容。
fn sh_shim_content(entry: &str) -> String {
    format!(
        "#!/bin/sh\n# Generated by dsh-tauri-desktop. Safe to delete.\nexec node \"{entry}\" \"$@\"\n"
    )
}

/// 解析当前 dsh 入口（若已安装核心；否则回退到 npx 方案）。
fn resolve_entry_for_shim() -> Option<String> {
    crate::services::core_service::resolve_active_entry()
        .ok()
        .map(|p| p.to_string_lossy().into_owned())
}

/// 安装 CLI shim 并注册 PATH。
pub async fn install_shim() -> AppResult<CliStatus> {
    let entry = resolve_entry_for_shim().ok_or_else(|| {
        AppError::NotFound("尚未安装 dsh 核心，无法注册 CLI（请先完成核心安装）".into())
    })?;

    path::ensure_dir(&path::bin_dir())?;
    if cfg!(windows) {
        install_windows(&entry).await
    } else {
        install_unix(&entry)
    }
}

async fn install_windows(entry: &str) -> AppResult<CliStatus> {
    let shim = path::bin_dir().join("dsh.cmd");
    std::fs::write(&shim, cmd_shim_content(entry))?;
    // 顺手生成无扩展名脚本，便于 Git Bash 等环境使用
    std::fs::write(
        path::bin_dir().join("dsh"),
        sh_shim_content(entry),
    )?;

    // 读取当前用户 PATH（注册表 HKCU\Environment\Path），不存在则创建
    let output = tokio::process::Command::new("reg")
        .args(["query", "HKCU\\Environment", "/v", "Path"])
        .output()
        .await
        .map_err(|err| AppError::Message(format!("读取用户 PATH 失败: {err}")))?;
    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    let bin_dir_str = path::bin_dir().to_string_lossy().into_owned();

    let already = stdout.to_lowercase().contains(&bin_dir_str.to_lowercase());
    if !already {
        // 解析 reg query 输出中的当前 PATH 值（REG_EXPAND_SZ 或 REG_SZ 类型标记之后）
        let current = stdout
            .lines()
            .find(|line| line.trim_start().to_uppercase().starts_with("PATH"))
            .map(|line| {
                for marker in ["REG_EXPAND_SZ", "REG_SZ"] {
                    if let Some(pos) = line.find(marker) {
                        return line[pos + marker.len()..].trim().to_string();
                    }
                }
                String::new()
            })
            .unwrap_or_default();
        let new_path = if current.is_empty() {
            bin_dir_str.clone()
        } else {
            format!("{current};{bin_dir_str}")
        };
        let set_output = tokio::process::Command::new("reg")
            .args(["add", "HKCU\\Environment", "/v", "Path", "/t", "REG_EXPAND_SZ", "/d", &new_path, "/f"])
            .output()
            .await
            .map_err(|err| AppError::Message(format!("写入用户 PATH 失败: {err}")))?;
        if !set_output.status.success() {
            return Err(AppError::Message(format!(
                "写入用户 PATH 失败: {}",
                String::from_utf8_lossy(&set_output.stderr)
            )));
        }
        tracing::info!("已将 {} 追加到用户 PATH", bin_dir_str);
    }

    Ok(CliStatus {
        shim_path: Some(shim.to_string_lossy().into_owned()),
        bin_dir_in_path: true,
        installed: true,
        message: "CLI 已注册（新开的终端窗口生效）".into(),
    })
}

fn install_unix(entry: &str) -> AppResult<CliStatus> {
    let local_bin = dirs::home_dir()
        .ok_or_else(|| AppError::Internal("无法定位用户目录".into()))?
        .join(".local")
        .join("bin");
    path::ensure_dir(&local_bin)?;
    let shim = local_bin.join("dsh");
    std::fs::write(&shim, sh_shim_content(entry))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&shim, std::fs::Permissions::from_mode(0o755))?;
    }

    let block = format!(
        "{BEGIN}\nexport PATH=\"$HOME/.local/bin:$PATH\"\n{END}\n",
        BEGIN = SHELL_BLOCK_BEGIN,
        END = SHELL_BLOCK_END
    );
    let mut updated_any = false;
    for rc in [".bashrc", ".zshrc"] {
        let Some(home) = dirs::home_dir() else { continue };
        let rc_path = home.join(rc);
        // 不存在的 rc 文件跳过（不主动创建，避免干扰用户 shell 选择）
        if !rc_path.exists() {
            continue;
        }
        let content = std::fs::read_to_string(&rc_path)?;
        if content.contains(SHELL_BLOCK_BEGIN) || content.contains(".local/bin") {
            continue; // 幂等：已有标记块或已有 .local/bin
        }
        let appended = format!("{content}\n{block}");
        std::fs::write(&rc_path, appended)?;
        updated_any = true;
        tracing::info!("已更新 shell 配置: {}", rc_path.display());
    }

    Ok(CliStatus {
        shim_path: Some(shim.to_string_lossy().into_owned()),
        bin_dir_in_path: true,
        installed: true,
        message: if updated_any {
            "CLI 已注册并更新 shell 配置（source 或重开终端生效）".into()
        } else {
            "CLI 已注册（~/.local/bin 已在 PATH 中）".into()
        },
    })
}

/// 查询 CLI 状态（不做任何修改）。
pub async fn status() -> CliStatus {
    let shim = if cfg!(windows) {
        path::bin_dir().join("dsh.cmd")
    } else {
        dirs::home_dir()
            .map(|h| h.join(".local/bin/dsh"))
            .unwrap_or_else(|| PathBuf::from("/nonexistent"))
    };
    let installed = shim.exists();
    let in_path = std::env::var_os("PATH")
        .map(|paths| std::env::split_paths(&paths).any(|p| p == path::bin_dir()))
        .unwrap_or(false);
    CliStatus {
        shim_path: installed.then(|| shim.to_string_lossy().into_owned()),
        bin_dir_in_path: in_path,
        installed,
        message: if installed {
            "CLI shim 已就绪".into()
        } else {
            "CLI 未安装".into()
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cmd_shim_forwards_args() {
        let content = cmd_shim_content("C:\\dsh\\bin\\dsh.js");
        assert!(content.contains("@echo off"));
        assert!(content.contains("%*"));
        assert!(content.contains("dsh.js"));
    }

    #[test]
    fn sh_shim_forwards_args() {
        let content = sh_shim_content("/opt/dsh/bin/dsh.js");
        assert!(content.starts_with("#!/bin/sh"));
        assert!(content.contains("\"$@\""));
        assert!(content.contains("exec node"));
    }

    #[test]
    fn shell_block_is_idempotent_marker() {
        let content = format!(
            "{BEGIN}\nexport PATH=\"$HOME/.local/bin:$PATH\"\n{END}\n",
            BEGIN = SHELL_BLOCK_BEGIN,
            END = SHELL_BLOCK_END
        );
        assert_eq!(
            content.matches(SHELL_BLOCK_BEGIN).count(),
            1,
            "标记块必须唯一以保证幂等"
        );
    }
}
